import React, { useState } from 'react';
import { Upload, Search, FileText, Download, Loader2, Book, Sparkles, AlertCircle, CheckCircle, XCircle } from 'lucide-react';



export default function ResearchAssistant() {
  const [documents, setDocuments] = useState([]);
  const [query, setQuery] = useState('');
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [activeTab, setActiveTab] = useState('upload');
  const [error, setError] = useState(null);

  const handleFileUpload = async (e) => {
    const files = Array.from(e.target.files);
    if (files.length === 0) return;

    setUploading(true);
    setError(null);
    
    const formData = new FormData();
    files.forEach(file => formData.append('files', file));
    
    try {
      const response = await fetch(`${API_BASE_URL}/upload`, {
        method: 'POST',
        body: formData
      });

      if (!response.ok) {
        throw new Error('Upload failed');
      }

      const data = await response.json();
      
      const newDocs = data.files.map(file => ({
        id: Math.random().toString(36).substr(2, 9),
        name: file.name,
        size: (file.size / 1024).toFixed(2) + ' KB',
        chunks: file.chunks,
        uploadedAt: new Date().toISOString()
      }));
      
      setDocuments([...documents, ...newDocs]);
      
    } catch (err) {
      setError('Failed to upload documents. Make sure the backend is running on port 5000.');
      console.error('Upload error:', err);
    } finally {
      setUploading(false);
    }
  };

  const handleSearch = async () => {
    if (!query.trim()) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(`${API_BASE_URL}/query`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query })
      });

      if (!response.ok) {
        throw new Error('Query failed');
      }

      const data = await response.json();
      
      setResults({
        answer: data.answer,
        rewrittenQuery: data.rewritten_query,
        sources: data.sources,
        searchType: data.search_type
      });
      
      setActiveTab('results');
      
    } catch (err) {
      setError('Failed to search. Make sure documents are uploaded and backend is running.');
      console.error('Search error:', err);
    } finally {
      setLoading(false);
    }
  };

  const exportReport = () => {
    const report = `
RESEARCH QUERY REPORT
=====================

Original Query: ${query}
Rewritten Query: ${results.rewrittenQuery}
Search Type: ${results.searchType}
Generated: ${new Date().toLocaleString()}

ANSWER:
${results.answer}

SOURCES:
${results.sources.map((s, i) => `
${i + 1}. ${s.document} (Page ${s.page})
   Relevance: ${(s.relevance * 100).toFixed(0)}%
   Excerpt: ${s.excerpt}
`).join('\n')}

BIBLIOGRAPHY:
${results.sources.map((s, i) => `[${i + 1}] ${s.document}`).join('\n')}

---
Generated by Intelligent Research Assistant
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `research_report_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-lg">
                <Book className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                  Intelligent Research Assistant
                </h1>
                <p className="text-sm text-gray-600">Advanced RAG Pipeline with Hybrid Search</p>
              </div>
            </div>
            <div className="text-sm text-gray-600">
              {documents.length} documents indexed
            </div>
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="max-w-7xl mx-auto px-6 mt-4">
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex items-start gap-3">
            <XCircle className="w-5 h-5 text-red-600 mt-0.5" />
            <div>
              <p className="text-red-800 font-medium">Error</p>
              <p className="text-red-600 text-sm">{error}</p>
            </div>
          </div>
        </div>
      )}

      {/* Navigation Tabs */}
      <div className="max-w-7xl mx-auto px-6 mt-6">
        <div className="flex gap-2 border-b border-gray-200">
          <button
            onClick={() => setActiveTab('upload')}
            className={`px-4 py-2 font-medium transition-all ${
              activeTab === 'upload'
                ? 'text-indigo-600 border-b-2 border-indigo-600'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            <Upload className="w-4 h-4 inline mr-2" />
            Upload Documents
          </button>
          <button
            onClick={() => setActiveTab('search')}
            className={`px-4 py-2 font-medium transition-all ${
              activeTab === 'search'
                ? 'text-indigo-600 border-b-2 border-indigo-600'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            <Search className="w-4 h-4 inline mr-2" />
            Search & Query
          </button>
          <button
            onClick={() => setActiveTab('results')}
            className={`px-4 py-2 font-medium transition-all ${
              activeTab === 'results'
                ? 'text-indigo-600 border-b-2 border-indigo-600'
                : 'text-gray-600 hover:text-gray-900'
            }`}
            disabled={!results}
          >
            <FileText className="w-4 h-4 inline mr-2" />
            Results
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        {activeTab === 'upload' && (
          <div className="space-y-6">
            {/* Upload Area */}
            <div className="bg-white rounded-xl shadow-lg border-2 border-dashed border-gray-300 hover:border-indigo-400 transition-all">
              <label className="flex flex-col items-center justify-center py-12 cursor-pointer">
                {uploading ? (
                  <Loader2 className="w-16 h-16 text-indigo-600 mb-4 animate-spin" />
                ) : (
                  <Upload className="w-16 h-16 text-gray-400 mb-4" />
                )}
                <span className="text-lg font-medium text-gray-700 mb-2">
                  {uploading ? 'Processing documents...' : 'Drop your research papers here'}
                </span>
                <span className="text-sm text-gray-500 mb-4">
                  Supports PDF, DOCX, TXT files
                </span>
                <input
                  type="file"
                  multiple
                  accept=".pdf,.docx,.txt"
                  onChange={handleFileUpload}
                  className="hidden"
                  disabled={uploading}
                />
                <div className={`px-6 py-2 rounded-lg transition-colors ${
                  uploading 
                    ? 'bg-gray-400 cursor-not-allowed' 
                    : 'bg-indigo-600 hover:bg-indigo-700 cursor-pointer'
                } text-white`}>
                  {uploading ? 'Processing...' : 'Browse Files'}
                </div>
              </label>
            </div>

            {/* Document List */}
            {documents.length > 0 && (
              <div className="bg-white rounded-xl shadow-lg p-6">
                <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                  <FileText className="w-5 h-5 text-indigo-600" />
                  Uploaded Documents ({documents.length})
                </h3>
                <div className="space-y-3">
                  {documents.map(doc => (
                    <div key={doc.id} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="p-2 bg-indigo-100 rounded">
                          <FileText className="w-5 h-5 text-indigo-600" />
                        </div>
                        <div>
                          <p className="font-medium text-gray-900">{doc.name}</p>
                          <p className="text-sm text-gray-500">{doc.size} • {doc.chunks} chunks</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <CheckCircle className="w-5 h-5 text-green-600" />
                        <span className="px-3 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-full">
                          Indexed
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Getting Started */}
            {documents.length === 0 && (
              <div className="bg-blue-50 rounded-xl p-6 border border-blue-200">
                <h3 className="font-semibold text-blue-900 mb-2">🚀 Getting Started</h3>
                <ol className="text-sm text-blue-800 space-y-2">
                  <li>1. Upload your research papers (PDF, DOCX, or TXT)</li>
                  <li>2. Wait for documents to be processed and indexed</li>
                  <li>3. Go to "Search & Query" tab to ask questions</li>
                  <li>4. View results with sources and export reports</li>
                </ol>
              </div>
            )}
          </div>
        )}

        {activeTab === 'search' && (
          <div className="space-y-6">
            {/* Search Box */}
            <div className="bg-white rounded-xl shadow-lg p-6">
              <label className="block text-sm font-medium text-gray-700 mb-3">
                Ask a research question
              </label>
              <div className="flex gap-3">
                <input
                  type="text"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                  placeholder="e.g., What are the latest advancements in transformer models?"
                  className="flex-1 px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none"
                  disabled={documents.length === 0}
                />
                <button
                  onClick={handleSearch}
                  disabled={loading || !query.trim() || documents.length === 0}
                  className="px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg hover:from-indigo-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 transition-all"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Searching...
                    </>
                  ) : (
                    <>
                      <Search className="w-5 h-5" />
                      Search
                    </>
                  )}
                </button>
              </div>
              
              <div className="mt-4 flex items-center gap-2 text-sm text-gray-600">
                <Sparkles className="w-4 h-4 text-purple-500" />
                <span>Using hybrid semantic + keyword search with query rewriting</span>
              </div>

              {documents.length === 0 && (
                <div className="mt-4 text-sm text-amber-600 flex items-center gap-2">
                  <AlertCircle className="w-4 h-4" />
                  Please upload documents first before searching
                </div>
              )}
            </div>

            {/* Info Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg p-4 border border-blue-200">
                <h4 className="font-semibold text-blue-900 mb-2">Semantic Search</h4>
                <p className="text-sm text-blue-700">Understands meaning and context of your query</p>
              </div>
              <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg p-4 border border-purple-200">
                <h4 className="font-semibold text-purple-900 mb-2">Query Rewriting</h4>
                <p className="text-sm text-purple-700">Optimizes your question for better results</p>
              </div>
              <div className="bg-gradient-to-br from-pink-50 to-pink-100 rounded-lg p-4 border border-pink-200">
                <h4 className="font-semibold text-pink-900 mb-2">Source Tracking</h4>
                <p className="text-sm text-pink-700">Every answer cites exact document and page</p>
              </div>
            </div>

            {/* Example Queries */}
            <div className="bg-white rounded-xl shadow-lg p-6">
              <h3 className="font-semibold mb-3">💡 Example Queries</h3>
              <div className="space-y-2">
                {[
                  "What are the main findings in this research?",
                  "Compare the methodologies used across documents",
                  "What are the limitations mentioned?",
                  "Summarize the key conclusions"
                ].map((ex, i) => (
                  <button
                    key={i}
                    onClick={() => setQuery(ex)}
                    className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-indigo-50 rounded-lg transition-colors"
                    disabled={documents.length === 0}
                  >
                    {ex}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {activeTab === 'results' && results && (
          <div className="space-y-6">
            {/* Query Rewriting Info */}
            <div className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-xl p-4 border border-purple-200">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-purple-600 mt-0.5" />
                <div className="flex-1">
                  <p className="text-sm font-medium text-gray-700 mb-1">Query Optimization</p>
                  <p className="text-sm text-gray-600"><span className="font-medium">Original:</span> {query}</p>
                  <p className="text-sm text-gray-600"><span className="font-medium">Rewritten:</span> {results.rewrittenQuery}</p>
                  <p className="text-xs text-purple-600 mt-1">Search Type: {results.searchType}</p>
                </div>
              </div>
            </div>

            {/* Answer */}
            <div className="bg-white rounded-xl shadow-lg p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-indigo-600" />
                  Answer
                </h3>
                <button
                  onClick={exportReport}
                  className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors text-sm"
                >
                  <Download className="w-4 h-4" />
                  Export Report
                </button>
              </div>
              <p className="text-gray-800 leading-relaxed whitespace-pre-wrap">{results.answer}</p>
            </div>

            {/* Sources */}
            <div className="bg-white rounded-xl shadow-lg p-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <FileText className="w-5 h-5 text-indigo-600" />
                Sources & Citations
              </h3>
              <div className="space-y-4">
                {results.sources.map((source, idx) => (
                  <div key={idx} className="border border-gray-200 rounded-lg p-4 hover:border-indigo-300 transition-colors">
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <span className="px-2 py-1 bg-indigo-100 text-indigo-700 text-xs font-bold rounded">
                          [{idx + 1}]
                        </span>
                        <p className="font-medium text-gray-900">{source.document}</p>
                      </div>
                      <div className="flex items-center gap-3">
                        <span className="text-sm text-gray-600">Page {source.page}</span>
                        <div className="flex items-center gap-1">
                          <div className="w-24 bg-gray-200 rounded-full h-2">
                            <div 
                              className="bg-green-500 h-2 rounded-full" 
                              style={{width: `${Math.min(source.relevance * 100, 100)}%`}}
                            />
                          </div>
                          <span className="text-xs text-gray-600 font-medium">
                            {Math.min(source.relevance * 100, 100).toFixed(0)}%
                          </span>
                        </div>
                      </div>
                    </div>
                    <p className="text-sm text-gray-600 italic bg-gray-50 p-3 rounded border-l-4 border-indigo-400">
                      "{source.excerpt}"
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Bibliography */}
            <div className="bg-white rounded-xl shadow-lg p-6">
              <h3 className="text-lg font-semibold mb-4">Bibliography</h3>
              <div className="space-y-2">
                {results.sources.map((source, idx) => (
                  <p key={idx} className="text-sm text-gray-700">
                    [{idx + 1}] {source.document}
                  </p>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="max-w-7xl mx-auto px-6 py-8 text-center text-sm text-gray-500">
        <p>Intelligent Research Assistant • Powered by RAG Pipeline</p>
        <p className="mt-1">Hybrid Search • Query Rewriting • Source Transparency</p>
      </div>
    </div>
  );
}
